<div class="container">
  <form>
  <h1>Registro Curso</h1>
    <div class="form-row">
      <div class="form-group col-md-6">
        <input type="text" class="form-control" placeholder="Ficha curso">
      </div>
      <div class="form-group col-md-6">
        <input type="text" class="form-control" placeholder="Curso">
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <select id="inputState" class="form-control">
        <option>Nivel curso</option>
      </select>
      </div>     
      <div class="form-group col-md-6">
        <select id="inputState" class="form-control">
        <option>Jornada</option>
      </select>
    </div>

    
    
    </div>

    <button class="btn btn-success col-6 offset-3">Guardar</button>

  </form>
</div>