<center><h1>Informe de Ubicación</h1></center>
<form >
<div class="form-group row">
    <label for="staticEmail" class="col-sm-12 col-form-label">Ambiente</label>
    <input type="text" class="form-control" placeholder="">
</div>
<div class="form-group row">
    <label for="staticEmail" class="col-sm-12 col-form-label">Feha Inicio</label>
    <input type="date" class="form-control" placeholder="">
</div>
<div class="form-group row">
    <label for="staticEmail" class="col-sm-12 col-form-label">Fecha Fin</label>
    <input type="date" class="form-control" placeholder="">
</div>
        
        <button class="btn btn-success col-md-6 offset-md-3">Descargar Registro</button>
    </form>   