  <div class="container">
    

    <form >
    <h1>Ingreso</h1>
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Documento">
        </div>
        <select class="form-control">
          <option>Ubicación</option>
        </select>
        <br>
        <h1>Salida</h1>
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Documento">
        </div>
        
        <button class="btn btn-success col-md-6 offset-md-3">Registrar</button>
    </form>   
    
  </div>