<div class="container">
  <form>
  <h1>Registro Usuario</h1>
    <div class="form-row">
      <div class="form-group col">
        <input type="text" class="form-control" placeholder="Nombre">
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        <select id="inputState" class="form-control">
        <option>Tipo documento</option>
      </select>
      </div>
      <div class="form-group col-md-8">
      <input type="text" class="form-control" placeholder="Documento">
      </div>      
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <select id="inputState" class="form-control">
          <option>Rol</option>
        </select>
      </div>
      <div class="form-group col-md-6">
        <select id="inputState" class="form-control">
          <option>Curso</option>
        </select>
      </div>
    
    </div>

    <button class="btn btn-success col-6 offset-3">Registrar</button>

  </form>
</div>