<center><H1>Ubicaciones</H1></center>
<div class="form-row">
      <div class="form-group col-md-12">
                <div class="span12">
                    <table class="table table-bordered table-striped table-hover table-condensed">
                        <TR>
                            <TH>Id</TH>
                            <TH>Ubicación</TH>
                            <TH>Detalles</TH>
                            <TH>Sede</TH>
                         </TR>
                         <TR>
                            <TD>Dato 1</TD>
                            <TD>Dato 2</TD>
                            <TD>Dato 3</TD>
                            <TD>Dato 4</TD>
                         </TR>
                    </table>
                    </div>
         </div>
      </div>